# Generated by Django 6.0.6 on 2026-09-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(choices=[(0, 'Matemáticas'), (1, 'Castelán'), (2, 'Galego'), (3, 'Historia de España'), (4, 'Historia da Filosofía'), (5, 'Inglés'), (6, 'Física'), (7, 'Químca'), (8, 'Bioloxía'), (9, 'Tecnoloxía'), (10, 'Debuxo Técnico'), (11, 'Métodos'), (12, 'Psicoloxía'), (13, 'Francés')])),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('period', models.IntegerField(choices=[(0, 'Matemáticas'), (1, 'Castelán'), (2, 'Galego'), (3, 'Historia de España'), (4, 'Historia da Filosofía'), (5, 'Inglés'), (6, 'Física'), (7, 'Químca'), (8, 'Bioloxía'), (9, 'Tecnoloxía'), (10, 'Debuxo Técnico'), (11, 'Métodos'), (12, 'Psicoloxía'), (13, 'Francés')])),
            ],
        ),
    ]
