# Generated by Django 6.0.6 on 2026-09-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='isConfirmed',
            field=models.BooleanField(default=True),
        ),
    ]
