# Generated by Django 6.0.6 on 2026-09-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exam_isconfirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.IntegerField(choices=[(0, 'Non Lectivo'), (1, 'Folga')])),
            ],
        ),
    ]
