# Generated by Django 6.0.6 on 2026-09-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_specialdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdate',
            name='event',
            field=models.IntegerField(choices=[(0, 'Non Lectivo'), (1, 'Folga'), (2, 'Avaliación')], default=0),
        ),
    ]
