# Generated by Django 6.0.6 on 2026-09-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_specialdate_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='period',
            field=models.IntegerField(choices=[(1, '1ª hora'), (2, '2ª hora'), (3, '3ª hora'), (4, '4ª hora'), (5, '5ª hora'), (6, '6ª hora'), (7, '7ª hora'), (8, 'Pola tarde')]),
        ),
    ]
